### ISSUE TITLE
TODO: improve developer docs

### ISSUE THREAD

**Issue by ihadeed** [ionic-team/ionic-native#1523]
- [ ] Ensure instructions are clear on how to build the library (complete build, or single plugin)
- [ ] Document all exported methods and decorators in the `@ionic-native/core` package with examples
- [ ] How to add a private wrapper/plugin from an Ionic 2 app without dealing with this repo
- [ ] Add a PR template to make the review process easier
  - PRs for fixes need to have link to original code with line number
  - PRs for new plugins need to have link to plugin repo

**Comment by evilstickman** [comment]
I will add to this "Returns Promise<any>" is useless when trying to develop. What is in the promise? What's the general structure? What data members can I rely being present in the promise's resolution handler?

Note - I'm referring to documentation at https://ionicframework.com/docs/native/google-plus/ and https://ionicframework.com/docs/native/facebook/ - all of the function calls give very, very little info on what to expect. Sure, the responses depend on the third-party APIs, but if that is the case say so instead of just saying "Returns: Promise<any>"
